---
version: "3"
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: not-secret
      POSTGRES_USER: wallabag

  redis:
    image: redis:alpine

  app:
    image: adborden/wallabag:latest
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_PASSWORD=not-secret
      - POSTGRES_USER=admin
      - SYMFONY_ENV=prod
      - DATABASE_DRIVER=pdo_pgsql
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=wallabag
      - DATABASE_USER=wallabag
      - DATABASE_PASSWORD=not-secret
      - DOMAIN_NAME=http://localhost:8080
      - WALLABAG_SECRET=27REwNFSfryeigy4jxZKL5fymczAVUxKXMLXzCyTb4OSMZLN9YxrZZOiJypEByvt
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - wallabag-www:/var/www/wallabag

  web:
    image: nginx:latest
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - wallabag-www:/var/www/wallabag

volumes:
  wallabag-www:
