---
parameters:
    database_driver: '%env(DATABASE_DRIVER)%'
    database_driver_class: ~
    database_host: '%env(DATABASE_HOST)%'
    database_port: '%env(DATABASE_PORT)%'
    database_name: '%env(DATABASE_NAME)%'
    database_user: '%env(DATABASE_USER)%'
    database_password: '%env(DATABASE_PASSWORD)%'
    database_path: ~
    database_table_prefix: wallabag_
    database_socket: ~
    database_charset: utf8
    domain_name: '%env(DOMAIN_NAME)%'
    mailer_transport: smtp
    mailer_user: ~
    mailer_password: ~
    mailer_host: 127.0.0.1
    mailer_port: false
    mailer_encryption: ~
    mailer_auth_mode: ~
    locale: en
    secret: '%env(WALLABAG_SECRET)%'
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: false
    fosuser_confirmation: false
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@wallabag.org
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: '%env(REDIS_HOST)%'
    redis_port: '%env(REDIS_PORT)%'
    redis_path: ~
    redis_password: ~
    sentry_dsn: ~
