---
name: Test

on:
  push:

env:
  PROD: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: make setup
      - name: lint
        run: make lint
      - name: build
        run: make build
      - name: test
        run: make test
      - name: snyk docker
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: adborden/wallabag:latest
          args: --file=Dockerfile
      - name: publish
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo -e '${{ secrets.DOCKERHUB_PASSWORD }}' | docker login --username '${{ secrets.DOCKERHUB_USERNAME }}' --password-stdin
          make publish
